### PR TITLE
Support for Legacy Data source Update

### PR DESCRIPTION
**Pull request by NandanHegde15**
Hey @liprec  :

Added support to update Legacy data source.
Legacy format :
ConnectionString   : Persist Security Info=false;User ID=abc@1;Encrypt=true;TrustServerCertificate=false;Data 
                     Source=abc.database.windows.net;Initial Catalog=xyz
ImpersonationMode  : ImpersonateServiceAccount

New format :
ConnectionDetails  : {"protocol":"tds","address":{"server":"abc.database.windows.net","database":"
                     xyz"},"authentication":null,"query":null}
Options            : {}
Credential         : {"AuthenticationKind":"UsernamePassword","Username":"abc@1","EncryptConnection":true,"Privac
                     ySetting":"Private"}

So for legacy sources, DataSources.connectionDetails is null thereby leading to False condition and going to else part

### CODE REVIEW

**Comment by NandanHegde15** [comment]
Hey @liprec .
Do I need to make any other changes in this PR ? To get it merged?
Because currently we are leveraging legacy source and for us to update, we have to have a separate task created to update the data sources. So want to avoid additional steps

**Comment by liprec** [comment]
Hi @NandanHegde15,

Sorry for the late reply and thanks for the PR.
But I am planning to add some more thing to the tasks that will include support for legacy data sources.

-JP

**Comment by NandanHegde15** [comment]
Hey @liprec ,
Thanks for the reply :)
So any ETA by when you would have the support ready for legacy sources?
And are you even planning to add: Retain existing roles and members task in that ? Because that was the next thing under my radar which I was working on.

**Comment by liprec** [comment]
Thanks for your PR and the change is included in the v1.3.5 release that is currently available.
The option to maintain roles and partition is not included and will in a future release.

**Pull request closed without merging**
